### ISSUE TITLE
User-Daten in Post-Meta-Tabelle verschlüsseln

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#141]

**Comment by thenickless** [comment]
Notizen für mich:

`Bookings -> bookingSubmitted() // Successful booking saved`
`Metaboxes -> booking()`

- [ ] rrze-rsvp-booking-guest-firstname

- [ ] rrze-rsvp-booking-guest-firstname

- [ ] rrze-rsvp-booking-guest-email

- [ ] rrze-rsvp-booking-guest-phone

**Comment by thenickless** [comment]
done in https://github.com/RRZE-Webteam/rrze-rsvp/commit/64cc2685bceb31c08339af078841ba4c72dc376a

Info:

User-Daten (Vorname, Nachname, eMail-Adr, Telefonnr) werden nun verschlüsselt gespeichert und entschlüsselt angezeigt zB in der Buchungsübersicht, dem Formular bzw für zB eMail und Tracking-CSV verwendet. Genutzt wird dazu Functions::crypt()
